blank_issues_enabled: false
contact_links:
  - name: English Support
    url: https://github.com/MeadalFlute/Create-Plus-Aeronautics/discussions
    about: Ask questions in Discussions
  - name: 中文支持
    url: https://github.com/MeadalFlute/Create-Plus-Aeronautics/discussions
    about: 在 Discussions 中提问
