// Visit the wiki for more info - https://kubejs.com/
console.info('Hello, World! (Loaded startup example script)')

StartupEvents.registry('item', event => {
  event.create('crushed_raw_tungsten')
  event.create('crushed_raw_titanium')
  event.create('incomplete_anvil_amulet')
  event.create('incomplete_cat_amulet')
  event.create('incomplete_dog_amulet')
  event.create('incomplete_cogwheel_amulet')
  event.create('incomplete_comrade_amulet')
  event.create('incomplete_emerald_amulet')
  event.create('incomplete_feather_amulet')
  event.create('incomplete_ruby_amulet')
  event.create('incomplete_sapphire_amulet')
  event.create('incomplete_silence_amulet')
  event.create('incomplete_topaz_amulet')
  event.create('incomplete_transcendium_ingot')
  event.create('raw_earth_core_shard')
  event.create('mixed_iron_and_gold_ingot')
  event.create('coal_dust')
  event.create('seeds_oil_residue').burnTime(120)
  event.create('pass')
})