LootJS.lootTables(event => {
    event.create("etc:food_vault_normal", "vault")
        .createPool(pool => {
            pool.addEntry(
                    LootEntry.of("createfood:chorus_fruit_cream_cake_chorus_fruit")
                        .withWeight(1) // 权重
                        .setCount(1) // 数量范围
                        .withQuality(2))
                .addEntry(
                    LootEntry.of("createfood:breakfast_plate")
                        .withWeight(2) // 权重
                        .setCount(1) // 数量范围
                        .withQuality(1))
                .addEntry(LootEntry.of("minecraft:golden_apple").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("minecraft:enchanted_golden_apple").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("mynethersdelight:golden_egg").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("mynethersdelight:enchanted_golden_egg").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("kaleidoscope_cookery:sweet_and_sour_pork").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("kaleidoscope_cookery:seafood_miso_soup").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("kaleidoscope_cookery:dongpo_pork").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("kaleidoscope_cookery:chorus_fried_egg").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("kaleidoscope_cookery:golden_salad").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("kaleidoscope_cookery:sweet_and_sour_ender_pearls").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("kaleidoscope_cookery:blaze_lamb_chop").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("kaleidoscope_cookery:end_style_sashimi").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("ends_delight:dragon_breath_and_chorus_soup").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("ends_delight:roasted_dragon_steak").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("ends_delight:assorted_salad").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("ends_delight:dragon_leg_with_sauce").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("ends_delight:steamed_dragon_egg").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("ends_delight:dragon_meat_stew").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("ends_delight:grilled_shulker").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("farmersdelight:apple_pie").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("farmersdelight:mixed_salad").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("farmersdelight:stuffed_potato").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("farmersdelight:pasta_with_meatballs").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("farmersdelight:mushroom_rice").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("farmersdelight:roasted_mutton_chops").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("farmersdelight:steak_and_potatoes").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("farmersdelight:squid_ink_pasta").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("farmersdelight:grilled_salmon").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("farmersdelight:roast_chicken").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("farmersdelight:shepherds_pie").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("farmersdelight:rice_roll_medley_block").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("mynethersdelight:fried_hoglin_chop").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("mynethersdelight:plate_of_stuffed_hoglin_snout").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("mynethersdelight:plate_of_stuffed_hoglin_ham").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("mynethersdelight:plate_of_stuffed_hoglin").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("mynethersdelight:bleeding_tartar").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("mynethersdelight:strider_with_grilled_fungus").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("mynethersdelight:crimson_stroganoff").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("mynethersdelight:plate_of_striderloaf").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("mynethersdelight:spicy_noodle_soup").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("mynethersdelight:plate_of_ghasta_with_cream").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("mynethersdelight:chilidog").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("mynethersdelight:spicy_hoglin_stew").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("mynethersdelight:spicy_curry").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("mynethersdelight:rock_soup").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("kaleidoscope_cookery:braised_beef").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("kaleidoscope_cookery:stir_fried_pork_with_peppers").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("createfood:apple_cheesecake").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("createfood:berry_jam_bottle").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("createfood:breakfast_plate").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("createfood:cheeseburger_onion_lettuce_tomato").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("createfood:chicken_cheeseburger_bacon_lettuce").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("createfood:chocolate_chip_milkshake_bottle").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("createfood:chocolate_cream_cake_white_chocolate").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("createfood:chorus_fruit_cream_donut").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("createfood:chorus_fruit_jam_sandwich").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("createfood:chorus_fruit_pie").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("createfood:dark_chocolate_apple").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("createfood:dragon_burger_crimson_fungus").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("createfood:endermite_meatball_sandwich").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("createfood:honeyed_berries").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("createfood:marshmallow_dark_chocolate").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("createfood:mushroom_onion_pizza").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("createfood:pasta_plate_strider_meatballs_tomato_sauce").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("createfood:sausage_mushroom_pizza").withWeight(2).setCount(1).withQuality(1))
                .addEntry(LootEntry.of("createfood:vegetable_sandwich_lettuce_tomato").withWeight(2).setCount(1).withQuality(1))
            

            pool.rolls([2,4])
            pool.bonusRolls(1)
        })
   
})